/*
  This file is automatically generated. Any changes will be overwritten.
  Modify démmarer-questionnaire.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { HeadingComponent } from '@radzen/angular/dist/heading';
import { FormComponent } from '@radzen/angular/dist/form';

import { ConfigService } from '../config.service';

import { PensionnairesDbService } from '../pensionnaires-db.service';

export class DemmarerQuestionnaireGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('pageTitle') pageTitle: HeadingComponent;
  @ViewChild('form0') form0: FormComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  pensionnairesDb: PensionnairesDbService;
  getPensionnairesResult: any;
  getQuestionnairesResult: any;
  parameters: any;
  pensionnaire: any;
  questionnaire: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.pensionnairesDb = this.injector.get(PensionnairesDbService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.pensionnairesDb.getPensionnaires(null, null, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.getPensionnairesResult = result.value;
    }, (result: any) => {

    });

    this.pensionnairesDb.getQuestionnaires(null, null, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.getQuestionnairesResult = result.value;
    }, (result: any) => {

    });
  }

  form0Submit(event: any) {
    this.pensionnaire = this.getPensionnairesResult;

    this.questionnaire = this.getQuestionnairesResult;

    if (this.dialogRef) {
      this.dialogRef.close();
    }
    this.router.navigate(['add-reponse']);
  }
}
